name: watching-mounts
base: core20
version: '0.2.2'
summary: Automatically mount USB and take actions
description: |
  This snap waits for USB plug events of block devices and automatically
  mounts such devices under the /media dir when inserted and then can take actions
grade: stable
confinement: strict

environment:
  LD_LIBRARY_PATH: $SNAP/usr/local/lib
  # Signal file to inform on-mount-do daemon the mount point of USB
  MOUNT: $SNAP_COMMON/mount
  UNMOUNT: $SNAP_COMMON/unmount
  LOG_SNAP_COMMON: $SNAP_COMMON/LOG.log
 
apps:
  udisksd:
    command: usr/local/libexec/udisks2/udisksd
    #install-mode: disable
    daemon: simple
    slots: [ service ]
    plugs:
      - hardware-observe
      - mount-observe
  automount:
    command: bin/automount
    daemon: simple
    after: [ udisksd ]
  autounmount:
    command: bin/autounmount
    daemon: simple
    after: [ udisksd ]
  udiskctl:
    command: bin/udiskctl.sh
    plugs:
      - block-devices
      - hardware-observe
      - mount-observe
  on-mount-do:
    command: bin/on-mount-do
    daemon: simple
  on-unmount-do:
    command: bin/on-unmount-do
    daemon: simple
  echo:
    command: bin/echo.sh

slots:
  service:
    interface: udisks2
plugs:
  client:
    interface: udisks2
  removable-media:
    interface: removable-media
  mount-observe:
  block-devices:
  hardware-observe:

layout:
  /var/lib/udisks2:
    bind: $SNAP_DATA/var/lib/udisks2
  /etc/libblockdev/conf.d:
    bind: $SNAP/etc/libblockdev/conf.d
  /usr/local/etc/udisks2:
    bind: $SNAP/usr/local/etc/udisks2
  /etc/crypttab:
    bind-file: $SNAP/etc/crypttab
  /usr/sbin/dumpe2fs:
    bind-file: $SNAP/usr/sbin/dumpe2fs

parts:
  launchers:
    source: launchers
    plugin: dump
  debs:
    plugin: nil
    stage-packages: [ curl, inotify-tools ] 
  pkgs:
    plugin: nil
    stage-packages: [ mount, e2fsprogs ]
    organize:
      sbin/dumpe2fs: usr/sbin/dumpe2fs
      bin/umount: usr/bin/umount
  udisks:
    source: https://github.com/storaged-project/udisks.git
    source-tag: udisks-2.8.4
    plugin: autotools
    override-pull: |
      snapcraftctl pull
      git apply -v ../../../udisksd.patch
    autotools-configure-parameters: ["--enable-fhs-media"]
    build-packages:
         - gnome-common
         - gobject-introspection
         - gtk-doc-tools
         - intltool
         - libacl1-dev
         - libatasmart-dev
         - libblockdev-btrfs-dev
         - libblockdev-crypto-dev
         - libblockdev-dev
         - libblockdev-dm-dev
         - libblockdev-fs-dev
         - libblockdev-kbd-dev
         - libblockdev-loop-dev
         - libblockdev-lvm-dbus-dev
         - libblockdev-lvm-dev
         - libblockdev-mdraid-dev
         - libblockdev-mpath-dev
         - libblockdev-part-dev
         - libblockdev-part-err-dev
         - libblockdev-swap-dev
         - libblockdev-utils-dev
         - libgirepository1.0-dev
         - libglib2.0-dev
         - libgudev-1.0-dev
         - libmount-dev
         - libpolkit-agent-1-dev
         - libpolkit-gobject-1-dev
         - libsystemd-dev
         - pkg-config
         - udev
         - xsltproc
    stage-packages:
        - libacl1
        - libatasmart4
        - libglib2.0-0
        - libgudev-1.0-0
        - libpam-systemd
        - libpolkit-agent-1-0
        - libpolkit-gobject-1-0
        - parted
        - libmount1
        - libblockdev2
        - libblockdev-swap2
        - libblockdev-loop2
        - libblockdev-crypto2
        - libblockdev-mdraid2
        - libblockdev-part2
        - libblockdev-fs2
    prime:
        - -lib/pkgconfig
        - -lib/systemd
        - -lib/cgmanager
