name: test-snapdapi
base: core20
version: 'demo-release'
summary: check for and do refresh every 5 sec 
description: |
  Demo. 
grade: stable
confinement: strict

apps:
  refresh-check:
    command: bin/refresh-check.sh
    daemon: simple
    plugs: [ snapd-control ]

plugs:
  network:
    interface: network
  snapd-control:
    interface: snapd-control

parts:
  debs:
    plugin: nil
    stage-packages: [ curl ] 
  launchers:
    source: launchers
    plugin: dump

